- name: Upgrade pip to latest
  ansible.builtin.pip:
    name: pip
    executable: pip3
    state: latest
  when: ansible_os_family == "Debian"

- name: Uninstall cloud-init pip package
  ansible.builtin.pip:
    name: "cloud-init"
    executable: pip3
    state: absent
  when: ansible_os_family == "Debian"

- name: Create dns default conf directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
  when: ansible_os_family == "Debian"

- name: Add default dns
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/default.conf
    content: |-
      [Resolve]
      DNS=8.8.8.8
    owner: root
    group: root
    mode: "0644"
  when: ansible_os_family == "Debian"