- name: Upgrade pip to latest
  ansible.builtin.pip:
    name: pip
    executable: pip3
    state: latest
  when: ansible_os_family == "Debian"

- name: Uninstall cloud-init pip package
  ansible.builtin.pip:
    name: "cloud-init"
    executable: pip3
    state: absent
  when: ansible_os_family == "Debian"